configName: sam_e54_xpro_freertos_keil
folderName: ''
format_version: v1.0
frameworkPath: D:\Projects\h3
processor: ATSAME54P20A
projectName: sdmmc_fat_sam_e54_xpro_freertos_keil
settings:
  PackageFilter: aws_cloud;bootloader;bsp;core;crypto;cryptoauthlib;csp;expresslogic_threadx;gfx;gfx_apps;net;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.3.64\atdf\ATSAME54P20A.atdf
