configName: sam_e54_xpro
folderName: sam_e54_xpro
format_version: v1.0
frameworkPath: ..\..\..\..\..
processor: ATSAME54P20A
projectName: basic_freertos_tickless_sam_e54_xpro
settings:
  PackageFilter: azure-rtos-threadx;bootloader_apps_ethernet;bootloader_apps_i2c;bootloader_apps_uart;bootloader_apps_usb;bsp;classb_sam_e5x_d5x;core;core_apps_sam_d21_da1;core_apps_sam_d5x_e5x;crypto;cryptoauthlib;csp;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;ethercat;gfx_apps;gfx_apps_sam_d5x_e5x;gfx_aria;mbed_os_rtos;mbed_os_rtos_apps;mc_apps_sam_d5x_e5x;net_apps_sam_a5d2;net_apps_sam_e5x;quick_docs;touch;touch_apps;wireless_system_pic32mzw1_wfi32e01;wireless_wifi;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.5.87\atdf\ATSAME54P20A.atdf
